[CAR] Controller, Service and Mapper
The-Champions-JV/Car-Sharing-Service pull request #9
Opened 2023-11-21 15:59 UTC by pastcwdt

2023-11-21 21:17 UTC, TetianaDenchyk requested changes
Good job! :)
Let's discuss and fix 
Update your branch, you will have security in it so that you can add **access by roles**
Add **swagger** also please

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +    @Transactional
You don't need Transactional here. You interact with DB only with save method
Check if it works without it

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +    @Transactional
Same here. Check if works without Transactional

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +    @Transactional
Same here. Check if works without Transactional
You don't interact with DB here

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +    @Transactional
Same

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +        updateValues(car, request);
This should be done with mapper

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/service/impl/CarServiceImpl.java
> +    }
Better delete this mapper and add method to mapper: 
`void updateCar(CreateCarRequestDto dto, @MappingTarget Car car);`
and use it in update method in service

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/controller/CarController.java
> +    @ResponseStatus(HttpStatus.OK)
It is default. You may remove it

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/controller/CarController.java
> +    public CarDto getById(@PathVariable Long id) {
Lets put @Positive annotation before Long id and @Validaded annotation above the controller

2023-11-21 21:17 UTC, TetianaDenchyk commented on src/main/java/com/champions/carsharingservice/controller/CarController.java
> +    public CarDto update(@PathVariable Long id, @RequestBody @Valid CreateCarRequestDto request) {
Same about responsestatus and @Positive

2023-11-22 14:57 UTC, Oleksandr-Tymoshenko approved these changes
Good, but pay attention to comments

2023-11-22 14:57 UTC, Oleksandr-Tymoshenko commented on src/main/java/com/champions/carsharingservice/controller/CarController.java
> +    public List<CarDto> getAll() {
you`ve forgotten about pageable

2023-11-22 14:57 UTC, Oleksandr-Tymoshenko commented on src/main/java/com/champions/carsharingservice/mapper/CarMapper.java
> +
remove blank line

2023-11-22 16:51 UTC, TetianaDenchyk approved these changes
I approve but you should add pageable in future

2023-11-22 17:19 UTC, merged